#!/bin/sh
export LD_LIBRARY_PATH=/hgsc_software/boost/boost-1.73.0/lib/:/hgsc_software/gcc/gcc-7.3.0/lib64:$LD_LIBRARY_PATH
main=/stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/data_eQTL
#fastqtl=/stornext/snfs5/ruichen/dmhg/fgi/jwang/software/fastqtl/bin/fastQTLe
fastqtl=/stornext/snfs5/ruichen/dmhg/fgi/jwang/software/fastqtl/python/run_FastQTL_threaded.py
#dir=$main/fastqtl_250kb_maf01_nsa4
#dir=$main/fastqtl_250kb_maf01_nsa4_cov_snRNAbatch
#dir=$main/fastqtl_250kb_maf01_nsa4_inPeak
dir=$main/fastqtl_500kb_maf01_nsa4_inPeak_5cpm_cellPeak 

mkdir ${dir}
pythonPass=/stornext/snfs5/ruichen/dmhg/fgi/jwang/miniconda3/bin/python3.7
#$pythonPass $fastqtl $main/../../WGS/WGS20more_chrAll.GATK.HaplotypeCaller.filtered.vcf_rmD017D020.gz_RS.gz $main/normalized_cmp_Rod_macular_24pp_bed_sort.gz Rod_macular_100chunks_10t --covariates $main/covariate_24pp_Rod --window 1e6 --ma_sample_threshold 3 --maf_threshold 0.05 --chunks 100 --threads 10 -o $main/fastqtl
#$pythonPass $fastqtl $main/../../WGS/WGS20more_chrAll.GATK.HaplotypeCaller.filtered_rmD017D020_RS_filtered.vcf_wH_flt_lcr_dosage.gz $main/normalized_cmp_Rod_macular_24pp_bed_sort.gz Rod_macular_100chunks_10t --covariates $main/covariate_24pp_Rod --window 1e6 --ma_sample_threshold 3 --maf_threshold 0.05 --chunks 100 --threads 10 -o $main/fastqtl
#/stornext/snfs5/ruichen/dmhg/fgi/jwang/software/fastqtl/bin/fastQTL --vcf /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/../../WGS/WGS20more_chrAll.GATK.HaplotypeCaller.filtered_rmD017D020_RS_filtered.vcf_wH_flt_lcr_dosage_plink_geno.gz --bed /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/normalized_cmp_${2}_macular_24pp_bed_sort.gz --window 1e6 --maf-threshold 0.05 --ma-sample-threshold 3 --interaction-maf-threshold 0 --cov /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/covariate_24pp_${2} --chunk ${1} 100 --out ${dir}/${2}_macular_100chunks_10t_chunk_${1}.txt.gz --log ${dir}/${2}_macular_100chunks_10t_chunk_${1}.log --seed 1602808477

#/stornext/snfs5/ruichen/dmhg/fgi/jwang/software/fastqtl/bin/fastQTL --vcf /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/../../WGS/WGS20more_chrAll.GATK.HaplotypeCaller.filtered_rmD017D020_RS_filtered.vcf_wH_flt_lcr_dosage_plink_geno.gz --bed /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/normalized_cmp_${2}_macular_24pp_bed_sort.gz --window 250000 --maf-threshold 0.1 --ma-sample-threshold 4 --interaction-maf-threshold 0 --cov /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/covariate_24pp_${2} --chunk ${1} 100 --out ${dir}/${2}_macular_100chunks_10t_chunk_${1}.txt.gz --log ${dir}/${2}_macular_100chunks_10t_chunk_${1}.log --seed 1602808477

#/stornext/snfs5/ruichen/dmhg/fgi/jwang/software/fastqtl/bin/fastQTL --vcf /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/../../WGS/WGS20more_chrAll.GATK.HaplotypeCaller.filtered_rmD017D020_RS_filtered.vcf_wH_flt_lcr_dosage_plink_geno.gz --bed /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/normalized_cmp_${2}_macular_24pp_bed_sort.gz --window 250000 --maf-threshold 0.1 --ma-sample-threshold 4 --interaction-maf-threshold 0 --cov /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/sc_eQTL/covariate_24pp_${2}_snRNA_batch --chunk ${1} 100 --out ${dir}/${2}_macular_100chunks_10t_chunk_${1}.txt.gz --log ${dir}/${2}_macular_100chunks_10t_chunk_${1}.log --seed 1602808477

/stornext/snfs5/ruichen/dmhg/fgi/jwang/software/fastqtl/bin/fastQTL --vcf /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/data/WGS20more_chrAll.GATK.HaplotypeCaller.filtered_rmD017D020_RS_filtered.vcf_wH_flt_lcr_dosage_plink_geno.gz --bed /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/data_eQTL/normalized_avg5cmp_${2}_pool_macular_20pp_afterSoupX_bed_sort.gz --window 500000 --maf-threshold 0.1 --ma-sample-threshold 4 --interaction-maf-threshold 0 --cov /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/data_eQTL/covariate_20pp_${2}_3peer_avg5cpm_afterSoupX --chunk ${1} 100 --out ${dir}/${2}_macular_100chunks_10t_chunk_${1}.txt.gz --log ${dir}/${2}_macular_100chunks_10t_chunk_${1}.log --seed 1602808477 --include-sites /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/data_eQTL/WGS20more_chrAll.GATK.HaplotypeCaller.filtered_rmD017D020_RS_filtered.vcf_wH_flt_lcr_dosage_plink_geno_site_inPeak_archr_new_${2} --exclude-samples  /stornext/snfs5/ruichen/dmhg/fgi/jwang/sc_human_retina/data/exclude_4sample
