#!/bin/sh
#for i in {1..5} {7..22} X
#for i in {1..5} {7..22}
#do
#/storage/chen/Software/bcftools/bin/bcftools index sc_human_retina/data/phase/1000GP_Phase3_20ppl_chr${i}.phased.wRef.ceu.vcf.correct_ref.gz
#/storage/chen/Software/bcftools/bin/bcftools index sc_human_retina/data/phase/1000GP_Phase3_20ppl_chr${i}.phased.wRef.oth.vcf.correct_ref.gz
#/storage/chen/Software/bcftools/bin/bcftools index sc_human_retina/data/phase/1000GP_Phase3_20ppl_chr${i}.phased.wRef.eas.vcf.correct_ref.gz

#/storage/chen/Software/bcftools/bin/bcftools merge sc_human_retina/data/phase/1000GP_Phase3_20ppl_chr${i}.phased.wRef.ceu.vcf.correct_ref.gz sc_human_retina/data/phase/1000GP_Phase3_20ppl_chr${i}.phased.wRef.oth.vcf.correct_ref.gz sc_human_retina/data/phase/1000GP_Phase3_20ppl_chr${i}.phased.wRef.eas.vcf.correct_ref.gz  -o sc_human_retina/data/phase/1000GP_Phase3_20ppl_chr${i}.phased.wRef.merge.vcf.correct_ref.gz -O z
#done
/storage/chen/Software/bcftools/bin/bcftools merge  /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D003_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D005_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D006_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D007_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D008_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D009_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D010_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D011_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/19_D019_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D005_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D009_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D013_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D017_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D018_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D019_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D021_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D026_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D027_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D028_13_phaser.vcf.gz /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/D030_13_phaser.vcf.gz -o  /storage/chen/home/jw29/sc_human_retina/data/ASE/phaser/20ppl_phaser_all.vcf.gz -O z
